# SPDX-License-Identifier: GPL-2.0+

include $(srctree)/drivers/log-level.mk
ccflags-y += $(call driver-log-flags,DRIVER_MMC)

obj-y += mmc-generic.o
obj-$(CONFIG_SOC_SUN20IW1) += mmc-sun20iw1.o
obj-$(CONFIG_SOC_SUN300IW1) += mmc-sun300iw1.o
obj-$(CONFIG_SOC_SUN50IW9) += mmc-sun50iw9.o
obj-$(CONFIG_SOC_SUN50IW10) += mmc-sun50iw10.o
obj-$(CONFIG_SOC_SUN55IW3) += mmc-sun55iw3.o
obj-$(CONFIG_SOC_SUN55IW6) += mmc-sun55iw6.o
obj-$(CONFIG_SOC_SUN60IW2) += mmc-sun60iw2.o
obj-$(CONFIG_SOC_SUN65IW1) += mmc-sun65iw1.o
obj-$(CONFIG_SOC_SUN8IW20) += mmc-sun8iw20.o
obj-$(CONFIG_SOC_SUN8IW21) += mmc-sun8iw21.o
obj-$(CONFIG_SOC_SUN8IW22) += mmc-sun8iw22.o
