# SPDX-License-Identifier: GPL-2.0+

TEST_TYPE := host
DT2C_DRIVER_SOURCES := drivers/intc/plic.c
DT2C_BINDINGS := dts/bindings/interrupt-controller/allwinner,sunxi-plic.yaml

include ../../mk/dt2c-host.mk
