[package]
name = "syterkit-xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.9", features = ["derive"] }
clap-verbosity-flag = "1.0"
log = "0.4"
env_logger = "0.9"
ctrlc = "3.2"
byteorder = "1"
