# SPDX-License-Identifier: GPL-2.0+

include $(srctree)/drivers/log-level.mk
ccflags-y += $(call driver-log-flags,DRIVER_DRAM)

obj-y += dram.o
obj-$(CONFIG_SOC_SUN20IW1) += dram-sun20iw1.o
obj-$(CONFIG_SOC_SUN252IW1) += dram-sun252iw1.o
obj-$(CONFIG_SOC_SUN300IW1) += dram-sun300iw1.o
obj-$(CONFIG_SOC_SUN50IW9) += dram-sun50iw9.o
obj-$(CONFIG_SOC_SUN50IW10) += dram-sun50iw10.o
obj-$(CONFIG_SOC_SUN55IW3) += dram-sun55iw3.o
obj-$(CONFIG_SOC_SUN55IW6) += dram-sun55iw6.o
obj-$(CONFIG_SOC_SUN60IW2) += dram-sun60iw2.o
obj-$(CONFIG_SOC_SUN65IW1) += dram-sun65iw1.o
obj-$(CONFIG_SOC_SUN8IW20) += dram-sun8iw20.o
obj-$(CONFIG_SOC_SUN8IW21) += dram-sun8iw21.o
obj-$(CONFIG_SOC_SUN8IW22) += dram-sun8iw22.o
