# SPDX-License-Identifier: GPL-2.0+
include $(srctree)/boards/Makefile.common
apps-y := extlinux_boot hello_world init_dram smhc_test syter_boot
obj-y += payloads/ar100s.o
board-libs-y := lib/libdram.a
