# SPDX-License-Identifier: GPL-2.0+

obj-y += timer.o exception.o memcpy.o memset.o fprw.o memcmp.o

obj-$(CONFIG_ARCH_RISCV32_CORE_E907) += riscv32_e907/
obj-$(CONFIG_ARCH_RISCV64_CORE_C906) += riscv64_c906/

ifeq ($(CONFIG_BACKTRACE),y)
obj-$(CONFIG_ARCH_RISCV32) += backtrace-rv32.o
obj-$(CONFIG_ARCH_RISCV64) += backtrace-rv64.o
endif
