/* SPDX-License-Identifier: GPL-2.0+ */
#ifndef _DT_BINDINGS_GPIO_SUNXI_GPIO_H
#define _DT_BINDINGS_GPIO_SUNXI_GPIO_H

#define SUNXI_GPIO_PORT_A 0
#define SUNXI_GPIO_PORT_B 1
#define SUNXI_GPIO_PORT_C 2
#define SUNXI_GPIO_PORT_D 3
#define SUNXI_GPIO_PORT_E 4
#define SUNXI_GPIO_PORT_F 5
#define SUNXI_GPIO_PORT_G 6
#define SUNXI_GPIO_PORT_H 7
#define SUNXI_GPIO_PORT_I 8
#define SUNXI_GPIO_PORT_J 9
#define SUNXI_GPIO_PORT_K 10
#define SUNXI_GPIO_PORT_L 11
#define SUNXI_GPIO_PORT_M 12
#define SUNXI_GPIO_PORT_N 13

#endif /* _DT_BINDINGS_GPIO_SUNXI_GPIO_H */
