# SPDX-License-Identifier: GPL-2.0+

TEST_TYPE := host
TEST_SRCS = $(srctree)/drivers/dram/dram.c
DT2C_DRIVER_SOURCES := drivers/dram/dram-sun20iw1.c
DT2C_BINDINGS := dts/bindings/memory/allwinner,sunxi-dram.yaml

include ../../mk/dt2c-host.mk
