// SPDX-License-Identifier: GPL-2.0+

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const TRACKED_ENV: &[&str] = &[
    "SYTERKIT_SOURCE_DIR",
    "SYTERKIT_FFI_HEADER_MANIFEST",
    "SYTERKIT_FFI_HEADERS",
    "SYTERKIT_FFI_ALLOWLIST",
    "SYTERKIT_FFI_ARCH",
    "SYTERKIT_FFI_CLANG_ARGS",
    "SYTERKIT_FFI_CONFIG",
    "SYTERKIT_FFI_AUTOCONF",
];

fn required_env(name: &str) -> String {
    env::var(name).unwrap_or_else(|_| panic!("{name} must be set when building SyterKit FFI"))
}

fn non_comment_lines(path: &Path) -> Vec<String> {
    let contents = fs::read_to_string(path)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));

    contents
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(ToOwned::to_owned)
        .collect()
}

fn resolve_path(source_dir: &Path, value: &str) -> PathBuf {
    let path = PathBuf::from(value);
    if path.is_absolute() {
        path
    } else {
        source_dir.join(path)
    }
}

fn discover_headers(root: &Path) -> Vec<PathBuf> {
    let mut headers = Vec::new();
    let mut directories = vec![root.to_path_buf()];

    while let Some(directory) = directories.pop() {
        println!("cargo:rerun-if-changed={}", directory.display());
        let entries = fs::read_dir(&directory)
            .unwrap_or_else(|error| panic!("cannot read {}: {error}", directory.display()));
        for entry in entries {
            let entry = entry
                .unwrap_or_else(|error| panic!("cannot inspect {}: {error}", directory.display()));
            let path = entry.path();
            if path.is_dir() {
                directories.push(path);
            } else if path.extension().is_some_and(|extension| extension == "h") {
                if path.file_name().is_some_and(|name| name == "trap.h")
                    && path
                        .parent()
                        .and_then(Path::file_name)
                        .is_some_and(|name| name == "asm")
                {
                    continue;
                }
                headers.push(path);
            }
        }
    }

    headers.sort();
    headers
}

fn headers_from_manifest(source_dir: &Path, manifest_path: &Path) -> Vec<PathBuf> {
    let mut headers = Vec::new();
    for entry in non_comment_lines(manifest_path) {
        if let Some(directory) = entry.strip_prefix("@all ") {
            headers.extend(discover_headers(&resolve_path(
                source_dir,
                directory.trim(),
            )));
        } else if entry == "@selected-arch" {
            let arch = required_env("SYTERKIT_FFI_ARCH");
            let directory = source_dir.join("arch").join(arch).join("include");
            headers.extend(discover_headers(&directory));
        } else if entry.starts_with('@') {
            panic!("unknown SyterKit FFI manifest directive: {entry}");
        } else {
            headers.push(resolve_path(source_dir, &entry));
        }
    }
    headers.sort();
    headers.dedup();
    headers
}

fn write_wrapper(out_dir: &Path, source_dir: &Path, headers: &[PathBuf]) -> PathBuf {
    let prelude = [
        source_dir.join("include/lib/fatfs/ff.h"),
        source_dir.join("include/lib/fdt/libfdt_env.h"),
        source_dir.join("include/lib/fdt/fdt.h"),
    ];
    let mut wrapper = String::from("/* Generated by syterkit-ffi; do not edit. */\n");

    for header in prelude
        .iter()
        .filter(|header| headers.iter().any(|selected| selected == *header))
    {
        wrapper.push_str("#include \"");
        wrapper.push_str(&header.to_string_lossy());
        wrapper.push_str("\"\n");
    }
    for header in headers {
        if prelude.iter().any(|selected| selected == header) {
            continue;
        }
        wrapper.push_str("#include \"");
        wrapper.push_str(&header.to_string_lossy());
        wrapper.push_str("\"\n");
    }

    let wrapper_path = out_dir.join("wrapper.h");
    fs::write(&wrapper_path, wrapper)
        .unwrap_or_else(|error| panic!("cannot write {}: {error}", wrapper_path.display()));
    wrapper_path
}

fn main() {
    for name in TRACKED_ENV {
        println!("cargo:rerun-if-env-changed={name}");
    }

    let source_dir = PathBuf::from(required_env("SYTERKIT_SOURCE_DIR"));
    let manifest_path = PathBuf::from(required_env("SYTERKIT_FFI_HEADER_MANIFEST"));
    let allowlist_path = env::var("SYTERKIT_FFI_ALLOWLIST")
        .ok()
        .filter(|path| !path.trim().is_empty())
        .map(PathBuf::from);

    println!("cargo:rerun-if-changed={}", manifest_path.display());
    if let Some(path) = &allowlist_path {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    for name in ["SYTERKIT_FFI_CONFIG", "SYTERKIT_FFI_AUTOCONF"] {
        if let Ok(path) = env::var(name) {
            if !path.is_empty() {
                println!("cargo:rerun-if-changed={path}");
            }
        }
    }

    let headers: Vec<PathBuf> = match env::var("SYTERKIT_FFI_HEADERS") {
        Ok(value) if !value.trim().is_empty() => value
            .split_whitespace()
            .map(|header| resolve_path(&source_dir, header))
            .collect(),
        _ => headers_from_manifest(&source_dir, &manifest_path),
    };

    if headers.is_empty() {
        panic!("SyterKit FFI header manifest contains no headers");
    }
    for header in &headers {
        if !header.is_file() {
            panic!("SyterKit FFI header does not exist: {}", header.display());
        }
        println!("cargo:rerun-if-changed={}", header.display());
    }

    let clang_args = env::var("SYTERKIT_FFI_CLANG_ARGS").unwrap_or_default();
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set"));
    let wrapper = write_wrapper(&out_dir, &source_dir, &headers);
    let mut builder = bindgen::Builder::default()
        .use_core()
        .layout_tests(false)
        .generate_comments(true)
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()));

    builder = builder.header(wrapper.to_string_lossy());
    for argument in clang_args.split_whitespace() {
        builder = builder.clang_arg(argument);
    }

    if let Some(allowlist_path) = allowlist_path {
        for rule in non_comment_lines(&allowlist_path) {
            let (kind, pattern) = rule.split_once(char::is_whitespace).unwrap_or_else(|| {
                panic!("invalid SyterKit FFI allowlist rule: {rule}");
            });
            let pattern = pattern.trim();
            if pattern.is_empty() {
                panic!("empty SyterKit FFI allowlist pattern: {rule}");
            }
            builder = match kind {
                "function" => builder.allowlist_function(pattern),
                "type" => builder.allowlist_type(pattern),
                "var" => builder.allowlist_var(pattern),
                _ => panic!("unknown SyterKit FFI allowlist rule: {kind}"),
            };
        }
    }

    let bindings = builder
        .generate()
        .unwrap_or_else(|error| panic!("unable to generate SyterKit Rust FFI bindings: {error}"));
    let output = out_dir.join("bindings.rs");
    bindings
        .write_to_file(&output)
        .unwrap_or_else(|error| panic!("cannot write {}: {error}", output.display()));
    println!("cargo:rustc-env=SYTERKIT_FFI_BINDINGS={}", output.display());
}
