# SPDX-License-Identifier: GPL-2.0+

TEST_TYPE := host
DT2C_DRIVER_SOURCES := drivers/gpio/gpio-v2.c drivers/pwm/pwm.c
DT2C_BINDINGS := dts/bindings/gpio/allwinner,sunxi-pinctrl.yaml \
	dts/bindings/pwm/allwinner,sunxi-pwm.yaml

include ../../mk/dt2c-host.mk
