# SPDX-License-Identifier: GPL-2.0+

TEST_TYPE := qemu-riscv
TEST_EXTRA_CPPFLAGS := -DSYTERKIT_BACKTRACE_TEST
TEST_EXTRA_SOURCES := $(CURDIR)/../../../arch/riscv/riscv32_e907/compiler_rt.c

include ../../mk/qemu-riscv.mk
