# SPDX-License-Identifier: GPL-2.0+
include $(srctree)/boards/Makefile.common
board-soc := sun8iw22
apps-sram-y := apps smp
apps-dram-y := apps
smp-y := smp.o
board-libs-y := $(soc-lib-dir)/libdram.a
