# SPDX-License-Identifier: GPL-2.0+

obj-y += clk.o
obj-$(CONFIG_SOC_SUN20IW1) += clk-sun20iw1.o
obj-$(CONFIG_SOC_SUN252IW1) += clk-sun252iw1.o
obj-$(CONFIG_SOC_SUN300IW1) += clk-sun300iw1.o
obj-$(CONFIG_SOC_SUN50IW9) += clk-sun50iw9.o
obj-$(CONFIG_SOC_SUN50IW10) += clk-sun50iw10.o
obj-$(CONFIG_SOC_SUN55IW3) += clk-sun55iw3.o
obj-$(CONFIG_SOC_SUN55IW6) += clk-sun55iw6.o
obj-$(CONFIG_SOC_SUN60IW2) += clk-sun60iw2.o
obj-$(CONFIG_SOC_SUN65IW1) += clk-sun65iw1.o
obj-$(CONFIG_SOC_SUN8IW20) += clk-sun8iw20.o
obj-$(CONFIG_SOC_SUN8IW21) += clk-sun8iw21.o
obj-$(CONFIG_SOC_SUN8IW22) += clk-sun8iw22.o
