/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef __SYSMAP_H__
#define __SYSMAP_H__

#include <reg-ncat.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PLAT_SYSMAP_BASE_ADDR (SUNXI_PLAT_TCIP_BASE_ADDR + 0xFFFF000)

#define SYSMAP_REGION_NUM 8

#define SYSMAP_MEM_ATTR_SO 0x10
#define SYSMAP_MEM_ATTR_CACHEABLE 0x8
#define SYSMAP_MEM_ATTR_BUFFERABLE 0x4

#define SYSMAP_MEM_ATTR_MASK (SYSMAP_MEM_ATTR_SO | SYSMAP_MEM_ATTR_CACHEABLE | SYSMAP_MEM_ATTR_BUFFERABLE)

#define SYSMAP_MEM_ATTR_SO_NC_NB (SYSMAP_MEM_ATTR_SO)
#define SYSMAP_MEM_ATTR_SO_NC_B (SYSMAP_MEM_ATTR_SO | SYSMAP_MEM_ATTR_BUFFERABLE)

#define SYSMAP_MEM_ATTR_WO_NC_NB (0)
#define SYSMAP_MEM_ATTR_WO_NC_B (SYSMAP_MEM_ATTR_BUFFERABLE)
#define SYSMAP_MEM_ATTR_WO_C_NB (SYSMAP_MEM_ATTR_CACHEABLE)
#define SYSMAP_MEM_ATTR_WO_C_B (SYSMAP_MEM_ATTR_CACHEABLE | SYSMAP_MEM_ATTR_BUFFERABLE)

#define SYSMAP_MEM_ATTR_DEVICE (SYSMAP_MEM_ATTR_SO_NC_NB)
#define SYSMAP_MEM_ATTR_RAM (SYSMAP_MEM_ATTR_WO_C_B)

#define SYSMAP_ADDR_SHIFT 12
#define SYSMAP_ADDR_ALIGN_SIZE (1 << SYSMAP_ADDR_SHIFT)
#define IS_MEM_ADDR_ALIGNED(addr) (!(addr & (SYSMAP_ADDR_ALIGN_SIZE - 1)))

void sysmap_dump_region_info(void);

#ifdef __cplusplus
}
#endif

#endif /* __SYSMAP_H__ */