# SPDX-License-Identifier: GPL-2.0+

TEST_TYPE := host
TEST_CPPFLAGS := -DDISBALE_COLOR_PRINTK
TEST_SRCS = $(srctree)/core/log/log.c $(srctree)/core/log/format.c \
	$(srctree)/lib/string.c

include ../../mk/host.mk
