# SPDX-License-Identifier: GPL-2.0+

TEST_TYPE := host
DT2C_DRIVER_SOURCES := drivers/intc/clic.c
DT2C_BINDINGS := dts/bindings/interrupt-controller/thead,c900-clic.yaml

include ../../mk/dt2c-host.mk
