# SPDX-License-Identifier: GPL-2.0+

TEST_TYPE := host
DT2C_DRIVER_SOURCES := drivers/dma/dma.c drivers/spi/spi.c
DT2C_BINDINGS := dts/bindings/dma/allwinner,sunxi-dma.yaml \
	dts/bindings/spi/allwinner,sunxi-spi.yaml

include ../../mk/dt2c-host.mk
