# SPDX-License-Identifier: GPL-2.0+
obj-y += remoteproc.o
obj-$(CONFIG_SOC_SUN20IW1) += rproc-sun20iw1.o
obj-$(CONFIG_SOC_SUN300IW1) += rproc-sun300iw1.o
obj-$(CONFIG_SOC_SUN50IW10) += rproc-sun50iw10.o
obj-$(CONFIG_SOC_SUN55IW3) += rproc-sun55iw3.o
obj-$(CONFIG_SOC_SUN8IW20) += rproc-sun8iw20.o
obj-$(CONFIG_SOC_SUN8IW21) += rproc-sun8iw21.o
