# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_APP_SRAM) += start.o

obj-$(CONFIG_EFEX) += efex.o

obj-$(CONFIG_APP_DRAM) += start.o

obj-y += compiler_rt.o exception.o timer.o
obj-y += mmu.o
obj-y += memcmp.o memcpy.o memset.o

obj-$(CONFIG_BACKTRACE) += backtrace.o
