# SPDX-License-Identifier: GPL-2.0+

include $(srctree)/drivers/log-level.mk
ccflags-y += $(call driver-log-flags,DRIVER_USB)
obj-y += usb_controller.o usb_device.o usb_lowlevel.o usb_manager.o function/ platform/
