# SPDX-License-Identifier: GPL-2.0+
include $(srctree)/boards/Makefile.common
board-soc := sun60iw2
apps-sram-y := hello_world
apps-dram-y := hello_world
board-libs-y := $(soc-lib-dir)/libdram-lpddr5.a
