# SPDX-License-Identifier: GPL-2.0+

obj-y += string.o ctype.o stdlib.o malloc.o
obj-y += elf/elf32.o elf/elf64.o
obj-y += fatfs/diskio.o fatfs/ff.o fatfs/ffsystem.o fatfs/ffunicode.o
obj-y += fdt/fdt.o fdt/fdt_empty_tree.o fdt/fdt_addresses.o
obj-y += fdt/fdt_overlay.o fdt/fdt_ro.o fdt/fdt_rw.o
obj-y += fdt/fdt_strerror.o fdt/fdt_sw.o fdt/fdt_wip.o
