/* SPDX-License-Identifier: GPL-2.0+ */

/**
 * @file head.c
 * @brief Boot0 file header definition for the Radxa Cubie A7Z (sun60iw2).
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <types.h>

/**
 * @struct boot_file_head
 * @brief Boot0 file header placed at the start of the boot image.
 *
 * This structure is placed at offset zero of the boot image so the BROM can
 * find the jump instruction and validate the image before executing it.
 */
typedef struct boot_file_head {
	uint32_t jump_instruction; /* one intruction jumping to real code */ /**< One instruction jumping to the real code. */
	uint8_t magic[8]; /* ="eGON.BT0" */ /**< Magic bytes identifying a boot0 image. */
	uint32_t check_sum; /* generated by PC */ /**< Checksum generated by the PC tool. */
	uint32_t *length; /* generated by LD */ /**< Length of the SPL image, filled by the linker. */
	uint32_t pub_head_size; /* the size of boot_file_head_t */ /**< Size of the boot_file_head_t structure. */
	uint8_t pub_head_vsn[4]; /* the version of boot_file_head_t */ /**< Version of the boot_file_head_t structure. */
	uint32_t *ret_addr; /* the return value */ /**< Return address used after boot. */
	uint32_t *run_addr; /* run addr */ /**< Address where the boot image is executed from. */
	uint32_t boot_cpu; /* eGON version */ /**< eGON boot CPU version. */
	uint8_t platform[8]; /* platform information */ /**< Platform information string. */
} boot_file_head_t;

#define BROM_FILE_HEAD_SIZE_OFFSET (((sizeof(boot_file_head_t) + sizeof(int)) / sizeof(int) + 1))
#define JUMP_INSTRUCTION (BROM_FILE_HEAD_SIZE_OFFSET | 0xEA000000)

#define BOOT0_MAGIC "eGON.BT0"
#define STAMP_VALUE (0x12345678)
#define BOOT_PUB_HEAD_VERSION "3000"

extern uint32_t __spl_size[];
extern uint32_t __code_start_address[];

/**
 * @brief The boot0 header instance emitted at the start of the boot image.
 *
 * The header is placed in the ".boot0_head" section so the BROM finds it at
 * the fixed offset expected by the boot protocol.
 */
const __attribute__((section(".boot0_head"))) boot_file_head_t boot_head = {
	.jump_instruction = JUMP_INSTRUCTION,
	.magic = BOOT0_MAGIC,
	.check_sum = STAMP_VALUE,
	.length = __spl_size,
	.pub_head_size = sizeof(boot_file_head_t),
	.pub_head_vsn = BOOT_PUB_HEAD_VERSION,
	.ret_addr = __code_start_address,
	.run_addr = __code_start_address,
	.boot_cpu = 0,
	.platform = { 0, 0, '3', '.', '0', '.', '0', 0 },
};