# SPDX-License-Identifier: GPL-2.0+

TEST_TYPE := qemu-riscv64
TEST_EXTRA_SOURCES := $(CURDIR)/../../../core/log/format.c
TEST_EXTRA_CPPFLAGS := -DFORMAT_RISCV64_TEST

include ../../mk/qemu-riscv64.mk
