/* SPDX-License-Identifier: GPL-2.0+ */

#include <drivers/serial/serial.h>

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <types.h>

#include <config.h>
#include <log.h>
#include <drivers/clk/clk.h>
#include <timer.h>

#include <common.h>
#include <jmp.h>
#include <mmu.h>
#include <malloc.h>
#include <stdlib.h>
#include <string.h>

#include <cli/cli.h>
#include <cli/cli_shell.h>
#include <cli/cli_termesc.h>

#include <drivers/dram/dram.h>
#include <dt-compatible/dram-dt.h>
#include <drivers/i2c/i2c.h>
#include <drivers/pmu/axp.h>
#include <dt-bindings/soc/sun50iw9.h>
#include <dt-compatible/i2c-dt.h>
#include <dt-compatible/mmc-dt.h>
#include <dt-compatible/rtc-dt.h>
#include <drivers/mmc/sdcard.h>
#include <drivers/soc/sid.h>
#include <drivers/spi/spi.h>

#include "fdt_wrapper.h"
#include <lib/fatfs/ff.h>
#include <lib/fatfs/diskio.h>
#include <lib/fdt/libfdt.h>
#include "uart.h"

static sunxi_dram_t dram;

#define CONFIG_BL31_FILENAME "bl31.bin"
#define CONFIG_BL31_LOAD_ADDR (0x48000000)

#define CONFIG_UBOOT_FILENAME "u-boot.bin"
#define CONFIG_UBOOT_LOAD_ADDR (0x4a000000)

#define CONFIG_DTB_FILENAME "sunxi.dtb"
#define CONFIG_DTB_LOAD_ADDR (0x4a200000)

#define CONFIG_KERNEL_FILENAME "Image"
#define CONFIG_KERNEL_LOAD_ADDR (0x40080000)

#define CONFIG_SDMMC_SPEED_TEST_SIZE 1024 // (unit: 512B sectors)

#define CONFIG_HEAP_BASE (0x40800000)
#define CONFIG_HEAP_SIZE (16 * 1024 * 1024)

extern sunxi_serial_t uart_dbg;

typedef struct atf_head {
	uint32_t jump_instruction; /* jumping to real code */
	uint8_t magic[8]; /* ="u-boot" */
	uint32_t scp_base; /* generated by PC */
	uint32_t next_boot_base; /* align size in byte */
	uint32_t nos_base; /* the size of all file */
	uint32_t secureos_base; /* the size of uboot */
	uint8_t version[8]; /* uboot version */
	uint8_t platform[8]; /* platform information */
	uint32_t reserved[1]; /* stamp space, 16bytes align */
	uint32_t dram_para[32]; /* the dram param */
	uint64_t dtb_base; /* the address of dtb */
} atf_head_t;

#define FILENAME_MAX_LEN 16
typedef struct {
	uint8_t *bl31_dest;
	char bl31_filename[FILENAME_MAX_LEN];

	uint8_t *uboot_dest;
	char uboot_filename[FILENAME_MAX_LEN];

	uint8_t *kernel_dest;
	char kernel_filename[FILENAME_MAX_LEN];

	uint8_t *of_dest;
	char of_filename[FILENAME_MAX_LEN];
} image_info_t;

image_info_t image;

#define CHUNK_SIZE 0x20000

static int fatfs_loadimage(char *filename, BYTE *dest)
{
	FIL file;
	UINT byte_to_read = CHUNK_SIZE;
	UINT byte_read;
	UINT total_read = 0;
	FRESULT fret;
	int ret;
	uint32_t start, time;

	fret = f_open(&file, filename, FA_OPEN_EXISTING | FA_READ);
	if (fret != FR_OK) {
		printk_error("FATFS: open, filename: [%s]: error %d\n", filename, fret);
		ret = -1;
		goto open_fail;
	}

	start = time_ms();

	do {
		byte_read = 0;
		fret = f_read(&file, (void *)(dest), byte_to_read, &byte_read);
		dest += byte_to_read;
		total_read += byte_read;
	} while (byte_read >= byte_to_read && fret == FR_OK);

	time = time_ms() - start + 1;

	if (fret != FR_OK) {
		printk_error("FATFS: read: error %d\n", fret);
		ret = -1;
		goto read_fail;
	}
	ret = 0;

read_fail:
	fret = f_close(&file);

	printk_debug("FATFS: read in %ums at %.2fMB/S\n", time, (f32)(total_read / time) / 1024.0f);

open_fail:
	return ret;
}

static int load_sdcard(image_info_t *image, sdmmc_pdata_t *card)
{
	FATFS fs;
	FRESULT fret;
	int ret;
	uint32_t start;

	uint32_t test_time;
	start = time_ms();
	sdmmc_blk_read(card, (uint8_t *)(dram.memory_base), 0, CONFIG_SDMMC_SPEED_TEST_SIZE);
	test_time = time_ms() - start;
	printk_debug("SDMMC: speedtest %uKB in %ums at %uKB/S\n", (CONFIG_SDMMC_SPEED_TEST_SIZE * 512) / 1024, test_time, (CONFIG_SDMMC_SPEED_TEST_SIZE * 512) / test_time);

	start = time_ms();

	mdelay(10);

	fret = f_mount(&fs, "", 1);
	if (fret != FR_OK) {
		printk_error("FATFS: mount error: %d\n", fret);
		return -1;
	} else {
		printk_debug("FATFS: mount OK\n");
	}

	printk_info("FATFS: read %s addr=%x\n", image->bl31_filename, (uint32_t)image->bl31_dest);
	ret = fatfs_loadimage(image->bl31_filename, image->bl31_dest);
	if (ret)
		return ret;

	// printk_info("FATFS: read %s addr=%x\n", image->uboot_filename, (uint32_t) image->uboot_dest);
	// ret = fatfs_loadimage(image->uboot_filename, image->uboot_dest);
	// if (ret)
	//     return ret;

	printk_info("FATFS: read %s addr=%x\n", image->of_filename, (uint32_t)image->of_dest);
	ret = fatfs_loadimage(image->of_filename, image->of_dest);
	if (ret)
		return ret;

	printk_info("FATFS: read %s addr=%x\n", image->kernel_filename, (uint32_t)image->kernel_dest);
	ret = fatfs_loadimage(image->kernel_filename, image->kernel_dest);
	if (ret)
		return ret;

	/* umount fs */
	fret = f_mount(0, "", 0);
	if (fret != FR_OK) {
		printk_error("FATFS: unmount error %d\n", fret);
		return -1;
	} else {
		printk_debug("FATFS: unmount OK\n");
	}
	printk_debug("FATFS: done in %ums\n", time_ms() - start);

	return 0;
}

void jmp_to_arm64(const sunxi_rtc_t *rtc, uint32_t addr)
{
	/* Set RTC data to current time_ms(), Save in RTC_FEL_INDEX */
	rtc_set_start_time_ms(rtc);

	/* set the cpu boot entry addr: */
	write32(RVBARADDR0_L, addr);
	write32(RVBARADDR0_H, 0);

	/* set cpu to AA64 execution state when the cpu boots into after a warm reset */
	asm volatile("mrc p15,0,r2,c12,c0,2");
	asm volatile("orr r2,r2,#(0x3<<0)");
	asm volatile("dsb");
	asm volatile("mcr p15,0,r2,c12,c0,2");
	asm volatile("isb");
_loop:
	asm volatile("wfi");
	goto _loop;
}

void set_pmu_fin_voltage(axp_pmu_t *pmu, char *power_name, uint32_t voltage)
{
	int temp_vol, src_vol = pmu_axp1530_get_vol(pmu, power_name);
	if (src_vol > voltage) {
		for (temp_vol = src_vol; temp_vol >= voltage; temp_vol -= 50) {
			pmu_axp1530_set_vol(pmu, power_name, temp_vol, 1);
		}
	} else if (src_vol < voltage) {
		for (temp_vol = src_vol; temp_vol <= voltage; temp_vol += 50) {
			pmu_axp1530_set_vol(pmu, power_name, temp_vol, 1);
		}
	}
	mdelay(30); /* Delay 300ms for pmu bootup */
}

int main(void)
{
	axp_pmu_t pmu;
	sdmmc_pdata_t boot_card = { 0 };
	sunxi_i2c_t i2c;
	sunxi_rtc_t rtc;
	sunxi_sdhci_t boot_mmc;

	if (sunxi_serial_init_stdout() != 0)
		return -1;

	show_banner();

	if (sunxi_i2c_dt_read_alias(&i2c, "i2c0") != DRIVER_OK || pmu_axp1530_config(&pmu, &i2c) != DRIVER_OK) {
		printk_error("PMU: invalid devicetree configuration\n");
		return -1;
	}
	if (sunxi_sdhci_dt_read_alias(&boot_mmc, "mmc0") != DRIVER_OK) {
		printk_error("SMHC: invalid devicetree configuration\n");
		return -1;
	}
	if (sunxi_rtc_dt_read_alias(&rtc, "rtc0") != DRIVER_OK) {
		printk_error("RTC: invalid devicetree configuration\n");
		return -1;
	}

	sunxi_clk_init();

	sunxi_clk_dump();

	sunxi_i2c_init(&i2c);

	pmu_axp1530_init(&pmu);

	set_pmu_fin_voltage(&pmu, "dcdc2", 1100);

	set_pmu_fin_voltage(&pmu, "dcdc3", 1100);

	/* Initialize the DRAM and enable memory management unit (MMU). */
	if (sunxi_dram_dt_read_alias(&dram, "dram0") != DRIVER_OK) {
		printk_error("DRAM: invalid devicetree configuration\n");
		return -1;
	}
	uint32_t dram_size = sunxi_dram_init(&dram);

	arm32_mmu_enable(dram.memory_base, dram_size);

	/* Initialize the small memory allocator. */
	malloc_init(CONFIG_HEAP_BASE, CONFIG_HEAP_SIZE);

	/* Clear the image_info_t struct. */
	memset(&image, 0, sizeof(image_info_t));

	image.bl31_dest = (uint8_t *)CONFIG_BL31_LOAD_ADDR;
	image.uboot_dest = (uint8_t *)CONFIG_UBOOT_LOAD_ADDR;
	image.of_dest = (uint8_t *)CONFIG_DTB_LOAD_ADDR;
	image.kernel_dest = (uint8_t *)CONFIG_KERNEL_LOAD_ADDR;

	strcpy(image.bl31_filename, CONFIG_BL31_FILENAME);
	strcpy(image.uboot_filename, CONFIG_UBOOT_FILENAME);
	strcpy(image.of_filename, CONFIG_DTB_FILENAME);
	strcpy(image.kernel_filename, CONFIG_KERNEL_FILENAME);

	/* Initialize the SD host controller. */
	if (sunxi_sdhci_init(&boot_mmc) != 0) {
		printk_error("SMHC: %s controller init failed\n", boot_mmc.name);
		goto _shell;
	} else {
		printk_info("SMHC: %s controller initialized\n", boot_mmc.name);
	}

	/* Initialize the SD card and check if initialization is successful. */
	if (sdmmc_init(&boot_card, &boot_mmc) != 0) {
		printk_warning("SMHC: init failed\n");
		goto _shell;
	}
	disk_set_device(0, &boot_card);

	/* Load the DTB, kernel image, and configuration data from the SD card. */
	if (load_sdcard(&image, &boot_card) != 0) {
		printk_warning("SMHC: loading failed\n");
		goto _shell;
	}

	atf_head_t *atf_head = (atf_head_t *)image.bl31_dest;

	atf_head->next_boot_base = CONFIG_UBOOT_LOAD_ADDR;
	atf_head->dtb_base = CONFIG_DTB_LOAD_ADDR;

	printk_info("ATF: jump_instruction: 0x%08x\n", atf_head->jump_instruction);
	printk_info("ATF: magic: %s\n", atf_head->magic);
	printk_info("ATF: scp_base: 0x%08x\n", atf_head->scp_base);
	printk_info("ATF: next_boot_base: 0x%08x\n", atf_head->next_boot_base);

	clean_syterkit_data();

	jmp_to_arm64(&rtc, CONFIG_BL31_LOAD_ADDR);

	printk_info("Back to SyterKit\n");

_shell:
	abort();

	return 0;
}
