# SPDX-License-Identifier: GPL-2.0+
include $(srctree)/boards/Makefile.common
apps-sram-y := cli_test fdt_cli fdt_parser hello_world i2c_oled i2c_test
apps-sram-y += load_e907 read_chip_efuse read_chipsid ruapu_test spi_lcd
apps-sram-y += syter_amp syter_boot syter_boot_sdnand syter_boot_spi syter_bootargs
apps-sram-y += usb_test
apps-efex-y := init_dram
apps-dram-y := hello_world
i2c_oled-y := oled.o
spi_lcd-y := lcd.o
