# SPDX-License-Identifier: GPL-2.0+
include $(srctree)/boards/Makefile.common
apps-y := cli_test fdt_cli fdt_parser hello_world i2c_oled i2c_test
apps-y += init_dram load_e907 read_chip_efuse read_chipsid ruapu_test spi_lcd
apps-y += syter_amp syter_boot syter_boot_sdnand syter_boot_spi syter_bootargs
apps-y += usb_test
i2c_oled-y := oled.o
spi_lcd-y := lcd.o
