name: Check

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Determine Rust or C check
        id: check_type
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | \
             grep -qE '^(rust/ | board/100ask-d1-h-rs/)'; then
            echo "rust_check=true" >> $GITHUB_ENV
          else
            echo "rust_check=false" >> $GITHUB_ENV
          fi

      - name: Run Cargo
        if: env.rust_check == 'true'
        uses: ./.github/workflows/Cargo.yml
      
      - name: Run CMake
        if: env.rust_check == 'false'
        uses: ./.github/workflows/CMake.yml
